"""
Mission Command Schema

Pydantic schema for natural language mission commands and planning.
Represents user input and mission execution status.
"""

from typing import Optional, List
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field, field_validator
from .robot_action import RobotAction


class MissionStatus(str, Enum):
    """Mission execution status."""
    PENDING = "pending"
    PLANNING = "planning"
    EXECUTING = "executing"
    VERIFYING = "verifying"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class MissionCommand(BaseModel):
    """
    Natural language mission command from user.

    Represents a mission request that will be:
    1. Analyzed by Planner Agent (natural language → action plan)
    2. Executed by Actor Agent (action plan → Webots commands)
    3. Verified by Verifier Agent (check success/failure)

    Example:
        >>> mission = MissionCommand(
        ...     command="3층 동쪽 구역에서 생존자 탐색, 위험 구역 회피",
        ...     language="ko"
        ... )
    """

    # Mission identification
    mission_id: Optional[str] = Field(
        default=None,
        description="Unique mission identifier (auto-generated if None)"
    )

    # User input
    command: str = Field(
        min_length=3,
        max_length=500,
        description="Natural language mission command in Korean or English"
    )

    language: str = Field(
        default="ko",
        pattern="^(ko|en)$",
        description="Command language: 'ko' (Korean) or 'en' (English)"
    )

    # Mission metadata
    priority: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Mission priority (1=lowest, 10=highest)"
    )

    timeout_seconds: float = Field(
        default=60.0,
        gt=0.0,
        le=300.0,
        description="Maximum mission execution time in seconds"
    )

    # Execution status
    status: MissionStatus = Field(
        default=MissionStatus.PENDING,
        description="Current mission status"
    )

    # Generated action plan
    action_plan: Optional[List[RobotAction]] = Field(
        default=None,
        description="Sequential action plan generated by Planner Agent"
    )

    # Execution tracking
    current_action_index: int = Field(
        default=0,
        ge=0,
        description="Index of currently executing action in plan"
    )

    # Starting position tracking (for relative movement verification)
    starting_position_x: Optional[float] = Field(
        default=None,
        description="Robot X position at mission start (for relative movement verification)"
    )

    starting_position_y: Optional[float] = Field(
        default=None,
        description="Robot Y position at mission start (for relative movement verification)"
    )

    starting_yaw: Optional[float] = Field(
        default=None,
        description="Robot heading (yaw in degrees) at mission start"
    )

    retry_count: int = Field(
        default=0,
        ge=0,
        le=5,
        description="Number of retry attempts (max 5)"
    )

    # Results
    success: Optional[bool] = Field(
        default=None,
        description="Mission success status (None=in progress, True/False=completed)"
    )

    result_message: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Detailed result or error message"
    )

    failure_reason: Optional[str] = Field(
        default=None,
        description="Reason for failure (if failed)"
    )

    # Timestamps
    created_at: datetime = Field(
        default_factory=datetime.now,
        description="Mission creation timestamp"
    )

    started_at: Optional[datetime] = Field(
        default=None,
        description="Mission execution start timestamp"
    )

    completed_at: Optional[datetime] = Field(
        default=None,
        description="Mission completion timestamp"
    )

    @field_validator("command")
    @classmethod
    def validate_command(cls, v: str) -> str:
        """Validate and normalize command string."""
        # Remove extra whitespace
        v = " ".join(v.split())

        # Allow any natural language command - Planner Agent will interpret
        return v

    @field_validator("retry_count")
    @classmethod
    def warn_high_retries(cls, v: int) -> int:
        """Warn if retry count is approaching limit."""
        if v >= 2:
            import warnings
            warnings.warn(
                f"Retry count is {v}/3. Mission may need reassessment.",
                UserWarning
            )
        return v

    def start_execution(self) -> None:
        """Mark mission as started."""
        self.status = MissionStatus.EXECUTING
        if self.started_at is None:
            self.started_at = datetime.now()

    def mark_completed(self, success: bool, message: str) -> None:
        """Mark mission as completed with result."""
        self.status = MissionStatus.COMPLETED if success else MissionStatus.FAILED
        self.success = success
        self.result_message = message
        self.completed_at = datetime.now()

    def mark_failed(self, reason: str) -> None:
        """Mark mission as failed with reason."""
        self.status = MissionStatus.FAILED
        self.success = False
        self.failure_reason = reason
        self.completed_at = datetime.now()

    def can_retry(self) -> bool:
        """Check if mission can be retried (max 3 retries)."""
        return self.retry_count < 3 and self.status == MissionStatus.FAILED

    def increment_retry(self) -> None:
        """Increment retry counter and reset status."""
        if self.can_retry():
            self.retry_count += 1
            self.status = MissionStatus.PENDING
            self.started_at = None
            self.completed_at = None
        else:
            raise ValueError("Maximum retry attempts (3) exceeded")

    def get_progress(self) -> float:
        """
        Calculate mission progress percentage.

        Returns:
            Progress from 0.0 to 100.0
        """
        if self.action_plan is None or len(self.action_plan) == 0:
            return 0.0

        if self.status == MissionStatus.COMPLETED:
            return 100.0

        return (self.current_action_index / len(self.action_plan)) * 100.0

    def get_elapsed_time(self) -> Optional[float]:
        """
        Get elapsed execution time in seconds.

        Returns:
            Elapsed seconds, or None if not started
        """
        if self.started_at is None:
            return None

        end_time = self.completed_at if self.completed_at else datetime.now()
        return (end_time - self.started_at).total_seconds()

    class Config:
        """Pydantic configuration."""
        json_schema_extra = {
            "examples": [
                {
                    "mission_id": "mission_001",
                    "command": "3층 동쪽 구역에서 생존자 탐색, 붕괴 위험 구역은 회피",
                    "language": "ko",
                    "priority": 8,
                    "timeout_seconds": 90.0,
                    "status": "executing",
                    "action_plan": [
                        {"action": "move", "x": 3.0, "y": 2.5, "speed": 1.0},
                        {"action": "scan", "duration": 5.0},
                        {"action": "rotate", "angle": 90.0}
                    ],
                    "current_action_index": 1
                },
                {
                    "command": "Navigate to safe zone and scan for survivors",
                    "language": "en",
                    "priority": 10,
                    "status": "completed",
                    "success": True,
                    "result_message": "Mission completed successfully. 2 survivors detected."
                }
            ]
        }
